language: node_js

os:
  - linux

node_js:
  - "8"

cache: yarn

script:
  - yarn
  - yarn build

before_install: yarn global add greenkeeper-lockfile
before_script: greenkeeper-lockfile-update
after_script: greenkeeper-lockfile-upload